name: haan_r_haan
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
  - family: Kanit
    fonts:
     - asset: assets/fonts/Kanit-Regular.ttf
     - asset: assets/fonts/Kanit-Italic.ttf
       style: italic
     - asset: assets/fonts/Kanit-Bold.ttf
       weight: 700
  - family: SFTHoNBURI
    fonts:
     - asset: assets/fonts/SFTHONBURI-REGULAR.TTF
     - asset: assets/fonts/SFTHONBURI-SEMIBOLD.TTF
       weight: 400
     - asset: assets/fonts/SFTHONBURI-BOLD.TTF
       weight: 700